meta_product_name: "Alice Gerelli Yoga"
meta_title: "Alice Gerelli Yoga - Pratichiamo Yoga insieme"
meta_description: "Alice Gerelli Insegnante certificata di Hatha Yoga e Vinyasa Yoga, appassionata di montagna e di natura in generale. Lezioni di Yoga online e in presenza."
meta_image: "stones.jpg" # should exist in `app/assets/images/`
